name: React.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Depedencies
        run: npm install

      # - name: Run lint
      #   run: npm run lint
      #  don't lint

      # - name: Run test
      #   run: npm test

      - name: Build production bundle
        run: npm run build

      - run: echo "🎉 semangat !"
